version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: trip_reservationsys_image_flask
    container_name: flask_trsfinal
    ports:
      - "5005:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: "1"